# dev-cluster.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  version: "$EKS_KUBE_VERSION" 
  name: $EKS_CLUSTER_NAME
  region: $AWS_REGION

autoModeConfig:
  enabled: false

# enable IAM roles for service accounts and OIDC provider
iam:
  withOIDC: true

vpc:
  nat:
    # each NAT Gateway costs $32.00 monthly. HighlyAvailable is $96.00 monthly
    # if you need to control the egress IP address of pods, you need to set it to Single or HighlyAvailable
    # if you don't need to control the egress IP address of pods, you can set it to Disable and save $32.00 monthly
    gateway: Single # other options: Disable, Single (default), HighlyAvailable


# add managed group for worker nodes
managedNodeGroups:
  - name: dev-ng-1-workers
    labels: { role: workers }
    # edit-this
    # Please visit https://instances.vantage.sh/ to check all available instance sizes
    # m5.large is $73.0000 monthly per instance
    # t3a.medium is $42.0000 monthly per instance
    instanceType: m5.large
    
    # edit-this
    desiredCapacity: 2
    maxPodsPerNode: 110
    # volumeSize: 100
    # volumeType: gp2
    
    # edit-this
    # uncomment the following line to enable encryption at rest for the node group
    volumeEncrypted: true
    # privateNetworking: true => if you want to use private networking for nodes (and control egress IP address of pods)
    # privateNetworking: true requires vpc.net.gateway to be set to Single or HighlyAvailable
    privateNetworking: true

# add EKS Pod Identity Agent (required for other addons using Pod Identity) and EBS CSI driver
addons:
- name: eks-pod-identity-agent
- name: aws-ebs-csi-driver
  resolveConflicts: preserve
  podIdentityAssociations:
    - namespace: kube-system
      serviceAccountName: ebs-csi-controller-sa
      permissionPolicyARNs: [arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy]

# need to be able to run 110 pods per node    
- name: vpc-cni
  # version: latest # Omit to automatically get the latest compatible version for $EKS_KUBE_VERSION
  configurationValues: "{\"env\":{\"ENABLE_PREFIX_DELEGATION\":\"true\", \"ENABLE_POD_ENI\":\"true\", \"POD_SECURITY_GROUP_ENFORCING_MODE\":\"standard\"}}"
  resolveConflicts: overwrite
  podIdentityAssociations:
    - namespace: kube-system
      serviceAccountName: aws-node
      permissionPolicyARNs: [arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy]
