# dev-cluster.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  version: "$EKS_KUBE_VERSION" 
  name: $EKS_CLUSTER_NAME
  region: $AWS_REGION

# enable IAM roles for service accounts and OIDC provider
iam:
  withOIDC: true

# add managed group for worker nodes
managedNodeGroups:
  - name: dev-ng-1-workers
    labels: { role: workers }
    # edit-this
    # Please visit https://instances.vantage.sh/ to check all available instance sizes
    # m5.large is $73.0000 monthly per instance
    instanceType: m5.large
    
    # edit-this
    desiredCapacity: 2
    maxPodsPerNode: 110
    # volumeSize: 100
    # volumeType: gp2
    
    # edit-this
    # uncomment the following line to enable encryption at rest for the node group
    # volumeEncrypted: true

# add EBS CSI driver (as an addon)
addons:
- name: aws-ebs-csi-driver
  resolveConflicts: preserve
  wellKnownPolicies:
    autoScaler: false
    awsLoadBalancerController: false
    certManager: false
    ebsCSIController: true
    efsCSIController: false

# need to be able to run 110 pods per node    
- name: vpc-cni
  # # Please visit https://docs.aws.amazon.com/eks/latest/userguide/managing-vpc-cni.html to pick the right version
  version: v1.17.1-eksbuild.1
  
  configurationValues: "{\"env\":{\"ENABLE_PREFIX_DELEGATION\":\"true\", \"ENABLE_POD_ENI\":\"true\", \"POD_SECURITY_GROUP_ENFORCING_MODE\":\"standard\"}}"
  resolveConflicts: overwrite
